// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file documentservice/v1/document.proto (package documentservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateDocumentRequest, CreateDocumentResponse, GetDocumentRequest, GetDocumentResponse } from "./document_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service documentservice.v1.DocumentService
 */
export const DocumentService = {
  typeName: "documentservice.v1.DocumentService",
  methods: {
    /**
     * @generated from rpc documentservice.v1.DocumentService.CreateDocument
     */
    createDocument: {
      name: "CreateDocument",
      I: CreateDocumentRequest,
      O: CreateDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc documentservice.v1.DocumentService.GetDocument
     */
    getDocument: {
      name: "GetDocument",
      I: GetDocumentRequest,
      O: GetDocumentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

